### PR TITLE
Add Docker Deployment

### PR DESCRIPTION
**Pull request by shibaobun**
## Features
- Dockerizes Forget
- Docker instructions added to readme

Please let me know if you have any questions about this PR! I'm also available on fedi at @shibao@misskey.bubbletea.dev

### CODE REVIEW

**Comment by shibaobun** [comment]
An issue with beat, going to sort it out and fix up a few things

**Comment by shibaobun** [comment]
Everything seems to be working and there's no errors in any of the logfiles, but for some reason it says
> Currently keeping track of 0 of your posts, roughly 0 of which currently match your expiration rules.

and doesn't seem to be deleting posts. I'm not sure if this is an unrelated bug or related to this deployment method (i'd suspect the latter, but i'm not sure).

**Comment by codl** [comment]
Hey, thanks for taking this on!

The counters being stuck at 0 is definitely not normal, I haven't had any reports of misskey incompatibilities lately. I can take a look next week, hopefully Monday.

Would you mind taking the workflow pushing to Docker Hub out of this PR? I'd rather first merge in a working Dockerfile that can be built locally, and then worry about automated builds.

**Comment by shibaobun** [comment]
I've adjusted the PR to build locally for now. Please let me know if there's any other changes that you'd like!

**Comment by shibaobun** [comment]
Ah, the issue was due to setting the queue, I'll fix that real quick and i think it works great

**Comment by shibaobun** [comment]
I'd like to blame doing this at 3am for most of this lol, should be good to go now though!

**Comment by shibaobun** [comment]
Let me actually try to get the log into the container output instead of a log file, for simplicity

**Comment by codl** [comment]
merged :) thanks

**Pull request merged**
